---
title: "microclimate_data"
author: "alayna"
date: "2025-05-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#library 
library(stringr)
library(dplyr)
library(ggridges)
library(viridis)
library(hrbrthemes)
library(ggplot2)
library(lubridate)
library(mgcv)

#read the file
micro <- read.csv("/Users/alaynatrejo/downloads/merged_dt_final.csv")

#View(micro)
```

```{r}

names(micro) <- tolower(names(micro)) 
#lowercases in columns^

#exclude rows with missing temp or time
micro_clean <- micro[is.finite(micro$temp_c) & !is.na(micro$time_observation), ]

#filter for .7 only 
micro_filter <- filter(micro_clean, confidence >=.7)

#View(micro_filter)

#storing date and time ... ex.20240118_083000
x <- c(micro_filter$time_observation)
#parse_date_time(x,"Ymd_HMS", tz = "GMT" ), H - mil. time
micro_filter$time_observation <- parse_date_time(x,"Ymd_HMS", tz = "GMT" )

#I'll separate graphs and results by double hashtags '##'

##temp and time graphed  
ggplot(micro_filter, aes(x = time_observation, y = temp_c, color = factor(elevation))) + 
  geom_line() + theme_minimal() + labs(title = "Temperature through time")

##temp n time w/ facet
ggplot(micro_filter, aes(x = time_observation, y = temp_c, color = factor(elevation))) + geom_smooth(method = "lm", se = FALSE) +
  geom_line() + facet_wrap( ~ elevation) + theme_minimal() + 
  labs(title = "Temperature through time")
```



```{r}
##claus o. wilke - credit: r graph gallery
ggplot(micro_filter, aes(x = temp_c, y = factor(elevation), fill = stat(x))) +
  geom_density_ridges_gradient(scale = 2, rel_min_height = 0.01) +
  scale_fill_viridis(name = "temp ", option = "C") +
  labs(title = "temperature distribution by elevation",
       x = "temp",
       y = "elevation band") +
  theme_ipsum() +
  theme(
    panel.spacing = unit(0.1, "lines"),
    strip.text.x = element_text(size = 8)
  )

##violin plot - credit: r graph gallery
micro_filter %>%
  ggplot(aes(x = factor(elevation), y = temp_c, fill = factor(elevation))) +
    geom_violin(trim = FALSE) +
    scale_fill_viridis(discrete = TRUE, alpha = 0.6, option = "A") +
    theme_ipsum() +
    theme(
      legend.position = "none",
      plot.title = element_text(size = 11)
    ) +
    ggtitle("temperature variance by elevation bands") +
    xlab("elevation band") +
    ylab("temp")

##best visualization for me
ggplot(micro_filter, aes(x = factor(elevation), y = temp_c, fill = factor(elevation))) + geom_boxplot() + theme_minimal() #must use factor for elevation (discrete x, continuous y)

```

```{r}

##relationship btwn elevation and temperature - insightful
model_elev_temp <- lm(temp_c ~ elevation, data = micro_filter)
summary(model_elev_temp)

##relationship btwn time and temperature
model_temp_time <- lm(temp_c ~ as.numeric(time_observation), data = micro_filter)
summary(model)

```


```{r}
#work for the GREEN warbler 

#green abundance 
green_micro <- micro_filter %>%
   filter(
  str_detect(common.name, regex("green", ignore_case = TRUE)))

#View(green_micro)

#detecting counts 
abundance_green <- green_micro %>%
  group_by(time_observation, temp_c, elevation) %>%
  summarise(detections = n(), .groups = "drop") %>%
  arrange(time_observation)

#View(abundance_green)

##temp n green w/o facet 
ggplot(abundance_green, aes(x = temp_c, y = detections, color = factor(elevation))) + geom_point() +
   theme_minimal() + labs(title = "Temperature v green detections")

##temp n green w/ facet 
ggplot(abundance_green, aes(x = temp_c, y = detections, color = factor(elevation))) + geom_point() + facet_wrap( ~ elevation) + theme_minimal() + labs(title = "Temperature v green detections")


gam_model <- gam(detections ~ s(temp_c) + s(elevation), data = abundance_green)
summary(gam_model)

```

```{r}
#work for the GREENISH warbler 

#greenish abundance 
greenish_micro <- micro_filter %>%
   filter(
    str_detect(common.name, regex("greenish", ignore_case = TRUE)))

#detecting counts 
abundance_ish <- greenish_micro %>%
  group_by(time_observation, temp_c, elevation) %>%
  summarise(detections = n(), .groups = "drop") %>%
  arrange(time_observation)

#View(abundance_ish)

##temp n greenish w/o facet 
ggplot(abundance_ish, aes(x = temp_c, y = detections, color = factor(elevation))) + geom_point() +
   theme_minimal() + labs(title = "Temperature v greenish detections")

##temp n greenish w/ facet 
ggplot(abundance_ish, aes(x = temp_c, y = detections, color = factor(elevation))) + geom_point() + facet_wrap( ~ elevation) + theme_minimal() + labs(title = "Temperature v greenish detections")

gam_model2 <- gam(detections ~ s(temp_c) + s(elevation), data = abundance_ish)
summary(gam_model2)

```

```{r}

#joint species info

#are there any temperature preferences?
 
ggplot(micro_filter, aes( x = common.name, y = temp_c, fill = common.name)) + geom_boxplot(alpha = 0.6) + scale_fill_viridis(discrete = TRUE, option = "A") + theme_minimal() + labs(title = "temperature by species")

t.test(temp_c ~ common.name, data = micro_filter)
```







